SET SCHEMA 'TaskStatistics';

DROP TABLE Task CASCADE;
CREATE TABLE Task(
	  TaskID		VARCHAR(16)		NOT NULL PRIMARY KEY
	, Name_			VARCHAR(60)
	, AverageUsage	DECIMAL(10,2)
);

DROP TABLE User_ CASCADE;
CREATE TABLE User_(
	  UserID		VARCHAR(256)		NOT NULL PRIMARY KEY
);

DROP TABLE Used CASCADE;
CREATE TABLE Used(
	  UserID		VARCHAR(256)		NOT NULL REFERENCES User_(UserID)
	, TaskID		VARCHAR(16)		NOT NULL REFERENCES Task(TaskID)
	, Hours			DECIMAL(10,2)
	, CONSTRAINT PK_constraint PRIMARY KEY(UserID,TaskID)
);

DROP TRIGGER UpdateAverageHours ON DATABASE;

CREATE TRIGGER UpdateAverageHours
AFTER INSERT OR UPDATE ON Used
FOR EACH ROW
EXECUTE PROCEDURE AverageHours();

CREATE OR REPLACE FUNCTION AverageHours()
	RETURNS TRIGGER AS $$
	BEGIN
		UPDATE Task r SET AverageUsage = (SELECT AVG(Hours) FROM Used u JOIN Task s ON u.TaskID=s.TaskID WHERE r.TaskID=u.TaskID);
		RETURN NULL;
	END;
	$$ LANGUAGE plpgsql;

SELECT * FROM Used;
SELECT * FROM User_;
SELECT * FROM Task;